name: 'dtmgr Action'
description: 'installs TeX Live with the packages listed for dtmgr'

runs:
  using: composite
  steps:
    - name: Read dtmgr
      id: read-dtmgr
      run: node ${{ github.action_path }}/dist/index.mjs
      shell: sh
    - name: Setup TeX Live
      uses: TeX-Live/setup-texlive-action@v3
      with:
        packages: ${{ steps.read-dtmgr.outputs.dtmgr_packages_list }}
